repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: local
    hooks:
      - id: lint-staged-and-test
        name: Lint Staged and Test
        entry: bash -c 'pnpm lint-staged && pnpm test'
        language: system
        pass_filenames: false
        stages: [commit]
